<?php

/**
 * @file
 * Contains ajaxtable.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ajaxtable_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ajaxtable module.
    case 'help.page.ajaxtable':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 * .html.twig file
 */
function ajaxtable_theme() {
  return [
    'ajaxtable' => [
      'render element' => 'children',
    ],
    // templates/render-by-template-form.html.twig
    'render_by_template_form' => [
      'render element' => 'form',
    ],
  ];
}
